/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package monitoringentry.admin.gui;

import monitoringentry.controller.MenuController;

/**
 *
 * @author M Arif Rosyanto
 */
public class PanelMaster extends javax.swing.JPanel {

    /**
     * Creates new form Panel
     */
    MenuController controller;
    public PanelMaster() {
        initComponents();
        
        controller = new MenuController(this,MainPanel, sidebarButton1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background1 = new monitoringentry.component.Background();
        MainPanel = new javax.swing.JPanel();
        Scroll1 = new javax.swing.JScrollPane();
        monitorPanel1 = new monitoringentry.chart.panel.MonitorPanel();
        Scroll2 = new javax.swing.JScrollPane();
        adminPanel2 = new monitoringentry.panelcomponent.AdminPanel();
        Scroll3 = new javax.swing.JScrollPane();
        usersPanel2 = new monitoringentry.panelcomponent.UsersPanel();
        Scroll4 = new javax.swing.JScrollPane();
        sidebarButton1 = new monitoringentry.panelcomponent.SidebarButton();
        LineHeader = new javax.swing.JPanel();
        Footer = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        MainPanel.setOpaque(false);
        MainPanel.setLayout(new java.awt.CardLayout());

        Scroll1.setViewportView(monitorPanel1);

        MainPanel.add(Scroll1, "dashboard");

        Scroll2.setViewportView(adminPanel2);

        MainPanel.add(Scroll2, "admin");

        Scroll3.setViewportView(usersPanel2);

        MainPanel.add(Scroll3, "users");
        MainPanel.add(Scroll4, "logout");

        LineHeader.setBackground(new java.awt.Color(255, 102, 0));
        LineHeader.setPreferredSize(new java.awt.Dimension(100, 6));

        javax.swing.GroupLayout LineHeaderLayout = new javax.swing.GroupLayout(LineHeader);
        LineHeader.setLayout(LineHeaderLayout);
        LineHeaderLayout.setHorizontalGroup(
            LineHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        LineHeaderLayout.setVerticalGroup(
            LineHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 6, Short.MAX_VALUE)
        );

        Footer.setBackground(new java.awt.Color(55, 55, 55));
        Footer.setPreferredSize(new java.awt.Dimension(100, 100));

        jLabel1.setForeground(new java.awt.Color(204, 204, 255));
        jLabel1.setText("Copyright DE-SE 2015");

        javax.swing.GroupLayout FooterLayout = new javax.swing.GroupLayout(Footer);
        Footer.setLayout(FooterLayout);
        FooterLayout.setHorizontalGroup(
            FooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FooterLayout.createSequentialGroup()
                .addGap(464, 464, 464)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        FooterLayout.setVerticalGroup(
            FooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FooterLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout background1Layout = new javax.swing.GroupLayout(background1);
        background1.setLayout(background1Layout);
        background1Layout.setHorizontalGroup(
            background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(background1Layout.createSequentialGroup()
                .addGap(270, 270, 270)
                .addComponent(LineHeader, javax.swing.GroupLayout.DEFAULT_SIZE, 1096, Short.MAX_VALUE))
            .addGroup(background1Layout.createSequentialGroup()
                .addComponent(sidebarButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(Footer, javax.swing.GroupLayout.DEFAULT_SIZE, 1366, Short.MAX_VALUE)
        );
        background1Layout.setVerticalGroup(
            background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(background1Layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(LineHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(background1Layout.createSequentialGroup()
                        .addComponent(MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 628, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Footer, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(sidebarButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(background1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(background1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Footer;
    private javax.swing.JPanel LineHeader;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JScrollPane Scroll1;
    private javax.swing.JScrollPane Scroll2;
    private javax.swing.JScrollPane Scroll3;
    private javax.swing.JScrollPane Scroll4;
    private monitoringentry.panelcomponent.AdminPanel adminPanel2;
    private monitoringentry.component.Background background1;
    private javax.swing.JLabel jLabel1;
    private monitoringentry.chart.panel.MonitorPanel monitorPanel1;
    private monitoringentry.panelcomponent.SidebarButton sidebarButton1;
    private monitoringentry.panelcomponent.UsersPanel usersPanel2;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the LineHeader
     */
    public javax.swing.JPanel getLineHeader() {
        return LineHeader;
    }
}
