/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package monitoringentry.panelcomponent;

import javax.swing.JButton;
import monitoringentry.component.MyButton;

/**
 *
 * @author M Arif Rosyanto
 */
public class SidebarButton extends javax.swing.JPanel {

    /**
     * Creates new form SidebarButton
     */
    public SidebarButton() {
        initComponents();
    }
    
    public void ActiveButton(MyButton a, MyButton b, MyButton c, MyButton d){
        a.Activebutton();
        b.resetButton();
        c.resetButton();
        d.resetButton();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dashboardButton1 = new monitoringentry.component.DashboardButton();
        adminButton1 = new monitoringentry.component.AdminButton();
        usersButton1 = new monitoringentry.component.UsersButton();
        logoutButton1 = new monitoringentry.component.LogoutButton();

        setOpaque(false);

        dashboardButton1.setText("");
        dashboardButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dashboardButton1ActionPerformed(evt);
            }
        });

        adminButton1.setText("");
        adminButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminButton1ActionPerformed(evt);
            }
        });

        usersButton1.setText("");
        usersButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usersButton1ActionPerformed(evt);
            }
        });

        logoutButton1.setText("");
        logoutButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dashboardButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(adminButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(usersButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(logoutButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(dashboardButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(adminButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(usersButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(logoutButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void dashboardButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dashboardButton1ActionPerformed
        ActiveButton(getDashboardButton1(), getAdminButton1(), getLogoutButton1(), getUsersButton1());
    }//GEN-LAST:event_dashboardButton1ActionPerformed

    private void adminButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminButton1ActionPerformed
        ActiveButton(getAdminButton1(), getDashboardButton1(), getLogoutButton1(), getUsersButton1());
    }//GEN-LAST:event_adminButton1ActionPerformed

    private void usersButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usersButton1ActionPerformed
        ActiveButton(getUsersButton1(), getDashboardButton1(), getAdminButton1(), getLogoutButton1());
    }//GEN-LAST:event_usersButton1ActionPerformed

    private void logoutButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButton1ActionPerformed
        ActiveButton(getLogoutButton1(), getDashboardButton1(), getAdminButton1(), getUsersButton1());
    }//GEN-LAST:event_logoutButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private monitoringentry.component.AdminButton adminButton1;
    private monitoringentry.component.DashboardButton dashboardButton1;
    private monitoringentry.component.LogoutButton logoutButton1;
    private monitoringentry.component.UsersButton usersButton1;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the adminButton1
     */
    public monitoringentry.component.AdminButton getAdminButton1() {
        return adminButton1;
    }

    /**
     * @return the dashboardButton1
     */
    public monitoringentry.component.DashboardButton getDashboardButton1() {
        return dashboardButton1;
    }

    /**
     * @return the logoutButton1
     */
    public monitoringentry.component.LogoutButton getLogoutButton1() {
        return logoutButton1;
    }

    /**
     * @return the usersButton1
     */
    public monitoringentry.component.UsersButton getUsersButton1() {
        return usersButton1;
    }
}
