/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package monitoringentry.chart.panel;

import java.awt.Dimension;
import monitoringentry.chart.CleanDataChart;
import monitoringentry.chart.UploadedDataChart;

/**
 *
 * @author Habib
 */
public class MonitorPanel extends javax.swing.JPanel {

    /**
     * Creates new form MonitorPanel
     */
    public MonitorPanel() {
        initComponents();
        setPreferredSize(new Dimension(800, 650));
        initChart();
    }
    private void initChart() {
        dataMasukPanel.setPreferredSize(new Dimension(300, 300));
        dataMasukPanel.add(new UploadedDataChart());
        cleanDataPanel.setPreferredSize(new Dimension(300, 300));
        cleanDataPanel.add(new CleanDataChart());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        dataMasukPanel1 = new javax.swing.JPanel();
        cleanDataPanel1 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        dataMasukPanel = new javax.swing.JPanel();
        cleanDataPanel = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        jPanel3.setLayout(new java.awt.BorderLayout());

        jPanel4.setLayout(new java.awt.GridLayout(2, 0));

        dataMasukPanel1.setLayout(new java.awt.BorderLayout());
        jPanel4.add(dataMasukPanel1);

        cleanDataPanel1.setLayout(new java.awt.BorderLayout());
        jPanel4.add(cleanDataPanel1);
        jPanel4.add(jPanel7);
        jPanel4.add(jPanel8);

        jPanel3.add(jPanel4, java.awt.BorderLayout.CENTER);

        jPanel9.setPreferredSize(new java.awt.Dimension(10, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("MONITORING ENTRY DATA PKL 54 BIDANG EKONOMI");
        jPanel9.add(jLabel2);

        jPanel3.add(jPanel9, java.awt.BorderLayout.PAGE_START);

        setOpaque(false);
        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.GridLayout(2, 0));

        dataMasukPanel.setOpaque(false);
        dataMasukPanel.setLayout(new java.awt.BorderLayout());
        jPanel1.add(dataMasukPanel);

        cleanDataPanel.setOpaque(false);
        cleanDataPanel.setLayout(new java.awt.BorderLayout());
        jPanel1.add(cleanDataPanel);

        jPanel5.setOpaque(false);
        jPanel1.add(jPanel5);

        jPanel6.setOpaque(false);
        jPanel1.add(jPanel6);

        add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.setPreferredSize(new java.awt.Dimension(10, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("MONITORING ENTRY DATA PKL 54 BIDANG EKONOMI");
        jPanel2.add(jLabel1);

        add(jPanel2, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel cleanDataPanel;
    private javax.swing.JPanel cleanDataPanel1;
    private javax.swing.JPanel dataMasukPanel;
    private javax.swing.JPanel dataMasukPanel1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    // End of variables declaration//GEN-END:variables

    
}
